A = {"Link number":"링크 번호",
"Disease":"질병",
"Country":"국가",
"Serotype":"혈청형",
"Report date":"보고일",
"report_type":"보고서 유형",
"report_ID":"보고서 ID",
"Causal agent":"원인체",
"Date of start of the outbreak":"발생일",
"Region":"지역",
"Epidemiological unit":"구분",
"Number of outbreaks":"건수",
"affected_population":"세부내역",
"index":"인덱스번호",
"SPECIES":"축종",
"Unnamed: 1":"미번호 1",
"MEASURING UNIT":"측정단위",
"SUSCEPTIBLE":"사육",
"CASES":"감염",
"DEATHS":"폐사",
"Killed and disposed of":"살처분",
"Slaughtered/Killed for commercial use":"도축",
"VACCINATED":"백신접종",
"Unnamed: 9":"미번호 9",
"Movement control inside the country":"국내이동제한",
"Vaccination in response to the outbreak (s)":"발생대응예방접종",
"Surveillance outside containment and or protection zone":"봉쇄지역 및/또는 보호지역 외 예찰",
"Surveillance within containment and or protection zone":"봉쇄지역 및/또는 보호지역 내 예찰",
"Screening,Traceability,Quarantine":"스크리닝",
"Official destruction of animal products":"동물성 생산물 공식처리",
"Official disposal of carcasses by-products and waste":"사체,부산물,폐기물 공식처리",
"Process to inactivate the pathogenic agent in products or by-products,Stamping out":"생산물 또는 부산물 내 병원체 불활화 처리",
"Selective killing and disposal":"선택적 살처분",
"Control of wildlife reservoirs":"야생보균원 관리",
"Zoning":"방역대 설정",
"Disinfection":"소독",
"Disinfestation":"해충구제",
"Control of vectors":"야생매개체 관리",
"Vector surveillance":"매개체 예찰",
"Ante and post-mortem inspections":"생,해체검사",
"Vaccination permitted (if a vaccine exists)":"백신접종 허용(백신이 있는 경우)",
"Vaccination prohibited":"백신접종 금지",
"No treatment of affected animals":"감염동물 미치료",
"Treatment of affected animals":"감염동물 치료",
"Slaughter":"도축*"}

c=list(B)